name: Build and Test mqtt-presence

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ğŸ› ï¸ Build and test on Python ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: âœ¨ Checkout repo
        uses: actions/checkout@v4


      - name: âš–ï¸ Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: â†‘ Install build tools and deps
        run: python -m pip install --upgrade pip build setuptools wheel pytest pylint toml


      - name: ğŸ•’ Run version update script
        run: python scripts/pre_build.py


      - name: ğŸ“¥ Install package and dependencies
        run: pip install .


      - name: ğŸ“¦ Build package
        run: python -m build
        

      - name: ğŸ§  Analysing the code with pylint
        run: python -m pylint $(git ls-files '*.py')

        
      - name: ğŸ§ª Run tests
        run: |
          if [ -d tests ]; then
            pytest tests
          else
            echo "No tests directory found."
          fi
