name: Pylint

on: 
  workflow_dispatch:
  #[push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: âœ¨ Checkout repo
        uses: actions/checkout@v4


      - name: âš–ï¸ Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: â†‘ Install build tools and deps
        run: python -m pip install --upgrade pip pylint toml


      - name: ğŸ•’ Run version update script
        run: python scripts/pre_build.py
      

      - name: ğŸ“¥ Install package and dependencies
        run: pip install .

      - name: ğŸ§  Analysing the code with pylint
        run: python -m pylint $(git ls-files '*.py')
